stages:
  preprocessing:
    cmd: python3 preprocessing/run_preprocessing_process.py
    deps: 
      - data/input
    params:
      - config.yaml:
          - preprocessing.fulfillment_mode
    outs:
      - data/preprocessed
      - data/artifacts/metadata

  training:
    cmd: python3 training/run_train_process.py
    deps:
      - data/preprocessed
    params:
      - config.yaml:
        - training.run_name
        - training.look_back
        - training.n_splits
        - training.train_dir_path
        - training.artifacts_dir_path
    outs:
      - data/artifacts/metrics
    metrics:
      - data/artifacts/metrics/rmse.json:
        - cache: false
      - data/artifacts/metrics/mape.json:
        - cache: false

  
